spring.application.name=Mini_Bank

spring.datasource.url=jdbc:mysql://localhost:3306/minibank_db
spring.datasource.username=root
spring.datasource.password=Sql@1110

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.main.web-application-type=servlet
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=always